### ISSUE TITLE
Add toggle functionality

### ISSUE THREAD

**Issue by marcelarie** [SidOfc/carbon.nvim#105]
It would be nice to have the toggle alternatives of all the Carbon commands.

`:CarbonToggle`:
goes back to the last buffer
`:LCarbonToggle`:
closes the LCarbon buffer, this can be triggered from any other buffer
`:FCarbonToggle`:
same as `LCarbonToggle`

**Comment by SidOfc** [comment]
Hello @marcelarie,

The names for these commands may seem a bit off, it seems like you want to be able to close Carbon buffers from any random buffer?

In the future, this will complicate things when I eventually merge support for showing multiple Carbon buffers where each buffer shows a different tree (e.g. via currently unsupported `:Carbon [path]`).

I also think that a toggle for `FCarbon` is tough to justify because this command spawns a popup which overlays other buffers thus you'll never navigate away from it without closing it, since it is in fact "in the way".

A "Toggle" command really only makes sense for `LCarbon` since there will only ever be exactly one pane which may not be the active buffer. Creating a toggle for it I think is already possible by calling `LCarbon` followed by `:close` which is a pretty simple mapping.

For reasons mentioned above I don't think I can justify implementing this feature but perhaps I'm not understanding you correctly, would you mind explaining in more detail what the goal is of this feature request?

**Comment by marcelarie** [comment]
> In the future, this will complicate things when I eventually merge support for showing multiple Carbon buffers where each buffer shows a different tree (e.g. via currently unsupported :Carbon [path]).
Hi @SidOfc, that feature sounds really nice.

Yes basically I am interested in closing the `:LCarbon` buffer from any other buffer, the other commands just come to mind when creating this feature request, but what you say makes sense. I think, anyway, a `:LCarbonToggle` command would be a nice feature.

**Comment by SidOfc** [comment]
Cool, glad I understood the request and that my reasoning about it is logical :)

I'll give this idea a spin when I have some time to see if it fits, or if I can make it fit otherwise. Thank you for your additional feedback!

**Comment by SidOfc** [comment]
Hello @marcelarie, I've implemented a command called `ToggleLcarbon` which functions similar to `Lcarbon` except when calling `ToggleLcarbon` when a window is already open, it will be closed.

This means it functions like an actual toggle which can also open the sidebar. I also added an additional setting to allow controlling whether or not to move the cursor to `Lcarbon` windows opened by `ToggleLcarbon`.

It's already merged into master so updating your plugins should pull the latest changes and allow you to try it out, if you find any issues with this feature please feel free to respond to this issue.

Will close for now since it is resolved, thank you for the suggestion 👍

**Comment by marcelarie** [comment]
Amazing news @SidOfc, thanks!
