### ISSUE TITLE
Mainteining alternate file

### ISSUE THREAD

**Issue by saccarosium** [SidOfc/carbon.nvim#109]
It would be nice if there was a setting that let you stop carbon to messing with the alternate file. When you press `C-^` you go to the previous edited file (aka alternate file).

## Current behaviour

https://user-images.githubusercontent.com/96259932/207969738-1f29f073-86f9-412c-9c09-bdb95e96b7a8.mov

Basecly, as you can see from the video, if you open another file by pressing `C-^` you go back to the previous file and vice versa. But if I open another file with carbon I alternate back an fourth between the recently opened file and the carbon buffer.

## Expected behaviour

https://user-images.githubusercontent.com/96259932/207970349-798d6683-47c2-4f6d-90e3-598c34c81f1b.mov

[Dirvish](https://github.com/justinmk/vim-dirvish) on the other hand when opens a file lets you go back and fourth between the previous file instead of the Dirvish buffer.

Hopefully I was clear enouth.

**Comment by SidOfc** [comment]
Well spotted, I personally fuzzy-find everything so I did not think about the utility which alternate file support could bring.

Adding some setting like `keepalt` would be nice for Carbon. The code in Dirvish requires some deeper understanding of VimL which I do not possess (or care to possess for that matter).

I will look into it but it will take some time since I'm not planning to work on Carbon this weekend and will still need to research how to do this properly in Lua once I start working on it.

Not sure yet whether or not this new `keepalt` setting will be `true` or `false` by default though, but that's something I'll break my head over later :D

Good idea, cheers 👍

**Comment by saccarosium** [comment]
I could try to help since I know a little bit of vimscript. I see if I can make a draft of a PR.

**Comment by SidOfc** [comment]
Sounds good 👍

**Comment by SidOfc** [comment]
Hello, I've just merged a patch which improves the behavior. It now works like this on file edit triggered via carbon:

- When there is _no_ alternate file yet, carbon will still set itself to the alternate file
- Once any alternate file is set, carbon will no longer set itself to the alternate file

This means that you can edit a file via carbon, navigate back using ctrl+^, select file 2, and you should then be able to jump back between the first opened file and the last one - skipping carbon in the process - using ctrl+^.

I do like this implementation so instead of putting it behind some setting, I've made it the default since it makes carbon interop better with Neovim.

Does this now work as you expected, or is there something I missed?

**Comment by saccarosium** [comment]
Just tested and works as expected. Thanks a lot.

**Comment by SidOfc** [comment]
Awesome, thank you once again for another good suggestion! Enjoy :)
