### ISSUE TITLE
How can I split the carbon view to the right?

### ISSUE THREAD

**Issue by sandangel** [SidOfc/carbon.nvim#111]
Hi, is it possible to toggle carbon viewer on the right hand side of the current buffer view?

**Comment by SidOfc** [comment]
Hi :)

Currently only an `LCarbon` command which toggles to the left exists. I did not build an `RCarbon` command though it shouldn't be too difficult to do I think.

**Comment by sandangel** [comment]
@SidOfc could you share the API how can I create RCarbon in my config, or it need to be done inside carbon?

**Comment by SidOfc** [comment]
@sandangel considering sidebars open files in other panes some special handling is needed which makes such snippet difficult to produce without actually going ahead and building the full feature. If you know some Lua though, you could try understanding [`carbon.explore_left`](https://github.com/SidOfc/carbon.nvim/blob/master/lua/carbon.lua#L190-L211) and building your own version perhaps.

If you're feeling really frisky, feel free to submit a PR if you plan to implement this yourself in Carbon :)

**Comment by SidOfc** [comment]
I've implemented the feature in the `feature/rexplore` branch, feel free to give it a spin if you want. It introduces a new command called `Rcarbon` (alias `Rexplore`) which opens the sidebar on the right side with files opening to the left.

In addition to that I renamed `ToggleLcarbon` to `ToggleSidebarCarbon` since it will act on either `Lcarbon` or `Rcarbon` sidebars.

The `ToggleSidebarCarbon` command will open to the left like `Lcarbon` by default. This can be changed via a setting called `sidebar_position`, setting it to `right` will cause the sidebar to show on the right side by default.

The base feature and most of the docs are already there but it's not finished yet. I figured I'd give you a heads up in case you already wanted to try it out :)

**Comment by sandangel** [comment]
oh nice. thanks very much for working on that. I think it's normal that people want to have it on the right so the current view won't be pushed to the left. I would love to give it a try.

**Comment by SidOfc** [comment]
Of course both sides are equally valid, no doubt. Initially though I implemented this "sidebar mode" as a bit of an afterthought since I don't personally use it, but wanted to provide something basic to supply this need out of the box. Since I see sidebars on the left 99.9% of the time (on YT, in real life) I implemented it just for that side initially ;)

As for trying it out, if you use a package manager, see if it allows you to configure a specific git branch and use `feature/explore-right` as branch name. Otherwise it's just pulling the latest changes from the repo and doing a `git checkout feature/explore-right`.

If you use Packer you may have to "recompile" (`:PackerCompile`) your configuration.

I'll be finishing this up somewhere this week so at worst you'll be able to update the stable version in 5-7 days :)

**Comment by SidOfc** [comment]
@sandangel feature has been merged into master, you should now be able to use aforementioned commands after updating to latest stable.

I will close this issue since the requested feature has been implemented, if there are additional expectations about how the right pane should behave feel free to add a comment here though :)

Cheers for the request 👍

**Comment by sandangel** [comment]
Wooooo. Thank you very much @SidOfc . This is amazing. I'm looking into this to replace neo-tree since it randomly crashing my neovim. I really love not only the effort you put into the plugin, but also kindly replied my requests. You're such a great open source maintainer. I really appreciate it.

**Comment by SidOfc** [comment]
Cheers for the kind words :)

Enjoy Carbon and thanks again for the feature request, it makes perfect sense to allow users to configure on which side the sidebar should appear.

Have a good one!
