### ISSUE TITLE
Is it possible to add file icons?

### ISSUE THREAD

**Issue by EpsilonKu** [SidOfc/carbon.nvim#112]
I couldn't find anything about icons on documentation. Is it possible to add file icons?

**Comment by SidOfc** [comment]
Currently this is not possible but given some time in the new year I can work on a feature to support this.

**Comment by SidOfc** [comment]
Hello, it's been a little while since the last reply here. Just wanted to inform I didn't forget about this request though I haven't started on it yet either.

I'm not exactly sure when I'll be working on this yet either, but probably soonish (somewhere within next two weeks).

Cheers for the patience!

**Comment by SidOfc** [comment]
Hi, I've implemented the base feature just now in branch [`feature/file-icons`](https://github.com/SidOfc/carbon.nvim/tree/feature/file-icons). It requires that [nvim-web-devicons](https://github.com/nvim-tree/nvim-web-devicons) is installed as well.

I'm not sure what package manager you use but if possible could you give this branch a spin? With [packer.nvim](https://github.com/wbthomason/packer.nvim) this can be achieved with the following snippet:

```lua
use({
  'SidOfc/carbon.nvim',
  branch = 'feature/file-icons',
  requires = { 'nvim-tree/nvim-web-devicons' },
  config = function()
    -- require('carbon').setup({ ... })
  end,
})
```

The feature is currently enabled by default when `nvim-web-devicons` is installed and disabled otherwise.

Most important bits if installing with any other package manager:
- make sure `nvim-web-devicons` is installed and _loaded before carbon.nvim_
- make sure that the `feature/file-icons` branch is installed instead of `master`

Please let me know what you think. Also let me know if these steps are too complicated.

**Comment by SidOfc** [comment]
Preview image (yours will likely differ due to theme):
<img width="306" alt="image" src="https://user-images.githubusercontent.com/3225058/211421507-b949e1c9-3a9e-460b-add4-361cca48529b.png">

**Comment by EpsilonKu** [comment]
Yeah, works perfect on `lazy.nvim`

**Comment by SidOfc** [comment]
Cheers for confirming, coming days I'll likely clean up and release a new version with this included :)

**Comment by SidOfc** [comment]
Closing this since the docs have now also been added as well :)

Thanks for the suggestion!
