### ISSUE TITLE
Partially overriding float_settings

### ISSUE THREAD

**Issue by Ansimorph** [SidOfc/carbon.nvim#115]
First of all thank you very much for carbon, I really like the simplicity of the project and how well it is tested.

I've run into a bit of an inconvenience when dealing with the float_settings: I want to change `height` and `row`. If I understand correctly I need to pass a function to `setup` that does supply all of the fields of `float_settings`:

```lua
require('carbon').setup {
  float_settings = function()
    local columns = vim.opt.columns:get()
    local rows = vim.opt.lines:get()
    local width = math.min(50, math.floor(columns * 0.8))
    local height = math.floor(rows * 0.8)

    return {
      style = 'minimal',
      relative = 'editor',
      border = 'single',
      width = width,
      height = height,
      col = math.floor(columns / 2 - width / 2),
      row = math.floor(rows / 2 - height / 2 - 2),
    }
  end,
}

```

This is a lot of code that just reinstates the defaults. Is there way to only change `height` and `row` and use the defaults for all other values of `float_settings`?

**Comment by SidOfc** [comment]
Hello there!

Cheers, glad carbon works for you :)

There is one other method you can use to configure carbon which involves using a callback:

```lua
require('carbon').setup(function(settings)
  -- other setting overrides

  function settings.float_settings()
    local original = settings.defaults.float_settings()

    return vim.tbl_extend('force', original, {
      -- put your overrides here
    })
  end
end)
```

This does require that you apply all your setting changes within this one function since `setup` cannot be called twice (additional calls will be ignored).

Perhaps I'm missing something though, if that seems to be the case then I'd like more information about what your ideal end result would look like :)

**Comment by Ansimorph** [comment]
Thanks, that is what I was looking for!

**Comment by SidOfc** [comment]
No problem, enjoy :)
