### ISSUE TITLE
Highlights are being cleared by colorscheme

### ISSUE THREAD

**Issue by datwaft** [SidOfc/carbon.nvim#12]
Hello!

I am currently beginning to use carbon.nvim and it seems that my colorscheme ([wuelnerdotexe/vim-enfocado](https://github.com/wuelnerdotexe/vim-enfocado)) is clearing the highlights used by carbon.nvim.

![image](https://user-images.githubusercontent.com/37723586/157798764-0337262d-e07c-4ce5-811e-19b32b1757af.png)

I created an small reproduction repository using Docker [here](https://github.com/datwaft/carbon.nvim_vim-enfocado_issue).

**Edit:** one possible fix could be using `highlight default` as can be seen in [`:hi-default`](https://vimhelp.org/syntax.txt.html#%3Ahi-default). I once had to use it for my plugin [corpus.vim](https://github.com/datwaft/corpus.vim). With it you don't need to use `after/syntax` or the like.

**Comment by SidOfc** [comment]
Hello again @datwaft,

I just pushed another patch which follows your suggestion of using `highlight default`. This is again another good sane default to set as well so that is a nice bonus 👍 

I'm leaving this one open for you to first confirm whether this patch does in fact fix your issue. Thanks again for the feedback from both issues!

**Comment by datwaft** [comment]
Thanks for your help, it seems that it doesn't work yet.

I tested it both on the reproduction repository and on my personal configuration and in both the highlights are still being cleared.

![image](https://user-images.githubusercontent.com/37723586/157994533-4c8b38c6-b726-4bc7-b552-a57db1206f0f.png)

**Comment by SidOfc** [comment]
Cheers for trying the patch, I did some additional research and found this in enfocado source code: https://github.com/wuelnerdotexe/vim-enfocado/blob/main/colors/enfocado.vim#L24-L30

It is in fact the other plugin which just blindly clears all highlights, Carbon uses the lua API to apply syntax highlighting instead of regular expressions. Additionally, Carbon is not a filetype plugin, it is a standalone file explorer.

For this type of plugin it makes sense to eager load syntax rather than being forced to put it in `/after/ftplugin` because some other plugin "forces" me to do so.

With that in mind I think you'd be best served by opening an issue on the enfocado repository instead as there will be more lua plugins which may opt to use the same syntax highlighting mechanism (`vim.api.nvim_buf_add_highlight`).

One thing I do not intend to do is shut anyone down of course, so I'm leaving the issue open for discussion for now :)

**Comment by SidOfc** [comment]
Specifically, this is related to plugins which are loaded through the `plugin` folder as opposed to the `ftplugin` folder. I do not think it is an issue with the `vim.api.nvim_buf_add_highlight` API but rather I think that no other plugin which applies highlights in the `plugin` directory will "work" though this is just an admittedly naive assumption 😅

**Comment by SidOfc** [comment]
Will mark this one resolved. If anyone reading this is experiencing this issue I doubt I can be of much help for reasons explained above however, I will remain open for potential solutions :)

**Comment by datwaft** [comment]
Thanks for you help! At the same time I opened this issue I also opened an issue on vim-enfocado that you can see here: https://github.com/wuelnerdotexe/vim-enfocado/issues/5.

Thanks for your help!

Btw, as a workaround I can set the highlights manually using what can be seen [here](https://github.com/wuelnerdotexe/vim-enfocado#customization), so it's not much of a problem.

**Comment by SidOfc** [comment]
Cheers for the reference link and repros @datwaft, much appreciated 👍 if enfocado does not want to add support I will add some enfocado specific section to the helpfile and add a note about it in the README.
