### ISSUE TITLE
When lazy loading Carbon via `lazy.nvim` an error is thrown

### ISSUE THREAD

**Issue by dhazel** [SidOfc/carbon.nvim#123]
Carbon is one of the best directory tree plugins for my workflow. Thanks!

When loading Carbon via lazy.nvim the following error is thrown.

```
Failed to run `config` for carbon.nvim

...a/Local/nvim-data/lazy/carbon.nvim/lua/carbon/buffer.lua:99: E565: Not allowed to change text or change window

# stacktrace:
  - carbon.nvim\lua\carbon\buffer.lua:99 _in_ **show**
  - carbon.nvim\lua\carbon\buffer.lua:22 _in_ **launch**
  - carbon.nvim\lua\carbon.lua:89 _in_ **initialize**
  - carbon.nvim\lua\carbon.lua:29 _in_ **setup**
3 fewer lines; before #1  2 seconds ago
```

It appears that there may be a textlock set when the buffer initialization attempts to run.

Note that Carbon *does* still manage to render, despite the error.

I will attach [a little pull request](https://github.com/SidOfc/carbon.nvim/pull/124), that removes the error on my box, as one possible solution; though, I am not familiar with Carbon's codebase enough to be sure that what I did is idiomatic.

**Comment by dhazel** [comment]
After playing around with this a bit, I recommend that, when people install Carbon using lazy.nvim, they apply the `lazy = false` flag. If they do that, then this error does not occur and Carbon will work the way it is intended to.

Example:
```lua
    {
      'SidOfc/carbon.nvim',
      lazy = false,
      init = function()
          vim.g.carbon_lazy_init = true
      end,
      opts = {
        -- sidebar_width = 45,
        -- sidebar_toggle_focus = false,
        -- auto_open = false,
      },
    }
```

Note, when using lazy.nvim, even though `lazy = false` is set, the `vim.g.carbon_lazy_init = true` needs to be set; otherwise, any options passed in will not be registered.

Doing those things above causes Carbon to work as expected.

I will close this issue since the config above works, and lazy loading is not needed (in my opinion).

**Comment by SidOfc** [comment]
Hey @dhazel, cheers for the positive impression! Glad you like it :)

I noticed that while I did "document" this lazy initialization behavior, I forgot to add a note to the README which refers to it. This has now been added to help prevent anyone from running into this and having to scan the carbon.txt doc file due to missing instruction details.

Wonderful description by the way, having an issue like this is definitely useful for when people end up missing the admittedly small note in the README section 👍
