### ISSUE TITLE
Automatically fold opened files

### ISSUE THREAD

**Issue by EpsilonKu** [SidOfc/carbon.nvim#125]
As title says, will be good to add option automatically fold.

**Comment by SidOfc** [comment]
Hello @EpsilonKu, to make sure I understand correctly, you are requesting a feature where all currently open files are automatically expanded in the file tree?

**Comment by SidOfc** [comment]
Hmn I'm not sure how I feel about implementing this. It does not sound difficult to implement but I wonder what benefit of automatically expanding the tree on _opening every file_ would be since I think it can be distracting users as well. Additionally, expanding the tree to show the file open in current buffer is already possible by adding an exclamation mark after the various explore commands that come with Carbon.

i.e. say you have some file `nested/file.txt` open in your editor, running `:Lcarbon!` or `Lexplore!` will show Carbon and expand the tree to show this file in addition to highlighting it for a short period of time as well.

Would this sufficiently cover your case? If not, could you elaborate on why you think expanding the tree every time to show any file being opened can be useful?

**Comment by EpsilonKu** [comment]
Ok, for me expanding only current file cover most of usage. So it's enough.

**Comment by SidOfc** [comment]
Cool, in that case I'm going to close this 👍

**Comment by SidOfc** [comment]
Oh I forgot to mention one thing @EpsilonKu, there is even a setting which causes reveal to be enabled for regular commands: `:h carbon-setting-always-reveal`
