### ISSUE TITLE
Open files in new tab

### ISSUE THREAD

**Issue by ironsigma** [SidOfc/carbon.nvim#131]
Add mapping to open files in new tab.

**Comment by SidOfc** [comment]
Hello @ironsigma, I've just implemented this feature, it is configured in `:h carbon-settings` as `actions.tabe` and defaults to key `<c-t>`. See `:h carbon-plug-tabe` for behavior.

I'll close this issue in advance but as usual if you see anything wrong or if I did not implement some expected behavior feel free to reopen so we can discuss 👍

**Comment by ironsigma** [comment]
That's wonderful thank you for such quick turn-around.

**Comment by SidOfc** [comment]
No problem, enjoy!
