### ISSUE TITLE
Is it possible to reveal the current buffer in the tree ?

### ISSUE THREAD

**Issue by jean-francois-labbe** [SidOfc/carbon.nvim#51]
I'd like to automatically expend the tree to see the current buffer.
It could be automatic or with a shortcut.

**Comment by jean-francois-labbe** [comment]
```
carbon_demo       < open vim in this folder
├── folder1
│   ├── info
│   └── readme.md
└── folder2
```

When i do :e folder1/readme.md, or fuzzy search the file.
Then :Lcarbon
I'd like to see the tree expanded according to the file I viewing.
![image](https://user-images.githubusercontent.com/1558372/179178129-16c102d7-88fd-4fbc-86b1-86c507a0fed8.png)


Here is a simple example from a new rails project.
![image](https://user-images.githubusercontent.com/1558372/179178604-3374fdd4-a720-4f56-b537-61fc5279cd05.png)

When I viewing the views/posts/index.html.erb file and want to see the files around it.
I'd type :Lcarbon and expect to see the tree expanded
Otherwise I have to open all the folds manually (search for the folder, open it, again and again).

Does it clarify the point ?

**Comment by SidOfc** [comment]
I see, yeah this seems like a good shortcut, I did not think about its use-case with `LCarbon` :)

Makes sense, marking this as a feature request and will see what I can come up with when I have some spare time on my hands.

Cheers for the suggestion and clarification 👍

**Comment by jean-francois-labbe** [comment]
I think it could be implemented as another command such as reveal current buffer.
it would expand the tree to the current file If Carbon is already opened.

**Comment by SidOfc** [comment]
I like your thinking, I have the same idea more or less, but instead of a new command, I was thinking to use the "bang" option in commands for this. If I generalize this feature a bit, it also makes sense at the very least for `FCarbon`, which also does not "replace" the current buffer with Carbon.

That said, even when using regular `Carbon` command, if you're on another buffer and want to expand Carbon to it I thought "why should it not be possible" and didn't find a good reason.

So with the reasoning above I think I want to do something like:

1. Introduce `Carbon!`, `FCarbon!`, `LCarbon!` and their aliases `Explore!` and `Lexplore!`
2. Providing a `!` will expand Carbon to the buffer that you are currently on

This allows you to use the bang versions to expand, and it'll always work :)

Some edge case is if the current file is not "in" the current working directory, I think I will no-op this with a warning.

Does this seem to make sense and otherwise fit your needs as well?

**Comment by jean-francois-labbe** [comment]
Yes it would fit my need.

To make it easier and more idempotent. I think `Lcarbon` should display in the same buffer and not create a new one.
This would make `Lcarbon!` calls easier to use repeatedly.

Should the tree revealed folders be updated according to the current buffer ?
Imagine you open Lcarbon! revealing the current file in the buffer. Then navigate to another file in a different folder.
I think it could be a configuration option to always keep the tree view in sync with the current buffer. 
I think it could be cumbersome in some cases. You might like to compare a folder content according to the content of a file in another folder.
For example compare the `app/views/posts/` (folder) according to the methods defined in the `app/controllers/posts_controller.rb` (file).

The first step is to provide the Carbon with the bang `!` to reveal current buffer.
Second if needed is the option to keep the tree revealed folders in sync with the current buffer.

**Comment by SidOfc** [comment]
@jean-francois-labbe hello,

The feature has been implemented, after updating you should be able to call `Lcarbon!` or `Lc!` etc and Carbon will reveal the path of the current buffer. Please let me know if you experience any issues with this specific functionality.

Going to work on the second point to navigate to existing buffers spawned via `Lcarbon` invocations.

**Comment by SidOfc** [comment]
Alright, also implemented the second point. Does everything work according to your expectations @jean-francois-labbe?

**Comment by SidOfc** [comment]
Oh, and if you do want to play around yourself with some vimscript/lua to try to emulate the behavior you seek w.r.t. keeping Carbon in sync, there is a `:h carbon-buffer-expand-to-path` method which you might find interesting. It is used by all the bang versions of the commands to expand the tree as well :)

**Comment by jean-francois-labbe** [comment]
Wow that was super fast. I'll let you know 😃
Thanks a lot for your reactivity.

**Comment by SidOfc** [comment]
While at it I also added a short "flash" highlight feature for revealed files (kind of like highlight on yank). It is enabled by default and highlights using `CarbonFlash` which by default links to `Search`.

It can be disabled by setting `:h carbon-setting-flash` to `nil`.

**Comment by SidOfc** [comment]
Hello @jean-francois-labbe, did you find the time to confirm everything works?

I'll close this issue since I don't expect it to "not" work. If you do find issues related to above features hit me up with a comment on this issue!

Last but not least, thank you for your time discussing this with me 👍 🎉

**Comment by jean-francois-labbe** [comment]
Thanks a lot @SidOfc . It works great.
I did not expected it that fast.
I'm on holiday. I'll spend some time setting the keybindings :)

That was a great pleasure to discuss this ticket with you.

Have a great day.

**Comment by SidOfc** [comment]
Hi @jean-francois-labbe, thank you for confirming, glad that expectations were exceeded in some regards :) Enjoy your holiday, the pleasure was mine!
