### ISSUE TITLE
Unable to open 

### ISSUE THREAD

**Issue by Mofiqul** [SidOfc/carbon.nvim#91]
Carbon stop working suddenly

![image](https://user-images.githubusercontent.com/23612580/189112216-c91c49f7-99a2-4f51-8d22-af5461690a55.png)

**Comment by SidOfc** [comment]
Hmn interesting, I did see something like this once or twice during development but didn't think much of it as I was still developing the plugin and haven't seen it since.

Now that this has resurfaced I'll check it out. I do have some extra questions though:

- How often does this happen?
- Is Carbon perhaps listening to a directory which often has a lot of changes? (e.g. files being regenerated by some build system)

**Comment by SidOfc** [comment]
I confirmed this broke when creating an entry pointing to a non-existent path and trying to list its children. This can happen when a directory is removed while synchronization is already in progress for example. Also assume this could happen when the directory is not accessible.

I've patched it by safeguarding this iteration process and confirmed it worked so I already closed the issue. You can update carbon.nvim and should no longer see this. That said, if you're still noticing issues please do comment on this issue as then it might require some additional research.

Thank you for reporting this 👍
