### ISSUE TITLE
More than one directory view

### ISSUE THREAD

**Issue by saccarosium** [SidOfc/carbon.nvim#94]
hi,
Currently only tree view is implemented. It would be really nice having also a view like default Netrw or [Dirvish](https://github.com/justinmk/vim-dirvish)

*dirvish*
![image](https://user-images.githubusercontent.com/96259932/202840340-a2c1872a-d1a2-460f-88c0-a7931677d2ed.jpeg)

**Comment by SidOfc** [comment]
There is a [branch](https://github.com/SidOfc/carbon.nvim/tree/insanity) which allows you to do stuff like `Carbon some/path` or `LCarbon some/path` or `FCarbon some/path`.

The branch is quite big so I've been testing it out myself, quite some work is still needed (documentation wise) before merging.

Does this branch fulfill your needs? Reason for asking is because in the screenshot I see a selection being made, and a command being executed on that selection, but I'm not sure what this does when executed, or what it has to do with a default view.

**Comment by saccarosium** [comment]
> Reason for asking is because in the screenshot I see a selection being made, and a command being executed on that selection, but I'm not sure what this does when executed, or what it has to do with a default view.

It's only the screenshot provided in the repo of vim Dirvish. I wanted only to have a visual representation of the beauvoir. 

> There is a branch which allows you to do stuff like Carbon some/path or LCarbon some/path or FCarbon some/path.

I will check it out

**Comment by SidOfc** [comment]
Let me know if you have problems running this branch, in this branch the entire `buffer.lua` module is replaced by a more generalized `view.lua` and this generalized module has not been documented yet.

Hopefully it isn't too painful to get working (been a while since I last touched the branch).
Awaiting feedback, cheers for checking!

**Comment by saccarosium** [comment]
I'm encountering 0 problems so far. But I don't see any changes in the way the directory are displayed.

**Comment by SidOfc** [comment]
So this is not about having the ability to view multiple directories, but rather showing the directory tree in a different type of view? I don't think we were talking about the same feature before, but I think I get it now. I'm not sure if this is something I'm willing to support though.

Just to make sure I have the right idea, you are requesting a "traditional" single-layer view where you only see one level of files / directories and have a `..` at the top to navigate back?

**Comment by SidOfc** [comment]
Hmn, the thing with Carbon is that it tries to show the tree structure of the current working directory as efficiently as possible i.e. by showing deeply nested paths directly you end up saving on amount of directory traversal you have to do.

This "default view" we are discussing will only show the content of one directory at a time and as such will not enjoy some of Carbon's intended core benefits. If a default view is all you use then I think you might not need/want Carbon.

Additionally, implementing multiple views increases surface area for bugs horizontally, meaning that every feature I then build which does something with the "view" must support mode X, Y, Z, etc... This is the route NetRW took and while I respect the author's urge to meet the needs of every user, it must have had a significant toll on code complexity.

A good example of this is having to tweak all the inline editing code for creating / moving / deleting files and directories. As this is currently fine-tuned for working with these "compressed" tree views.

It's not that I don't like the suggestion per-se, but thinking about all the extras I'd have to re-build, re-test, re-document it's not something I want to commit to. I still think it's good to have an issue like this though, where thoughts and opinions can accumulate which may at some point change my mind.

For now, I will close this one since I'm not going to work on this anytime soon, that said a closed issue is not at all invalid, and may be "revived" later :) In the meantime, thank you for opening the discussion 👍

**Comment by saccarosium** [comment]
I respect your decision and I will probably change my workflow and habits to work with carbon, because after using it for some times I see the appeal and strength. 

Really nice job!

**Comment by ViktorHefringMarine** [comment]
This is great. Exactly what I've been looking for.
